import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(channel="msedge", headless=False)
    context = browser.new_context(ignore_https_errors=True, viewport={"width":1600,"height":900})
    page = context.new_page()
    page.goto("https://ess.highbartech.com/hrms/login.aspx")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("Jayasurya.Lakkoju@highbartech.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Highbar@12345678")
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("link", name="ABAP Development Pending (1)").click()
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.get_by_role("row", name="Submit Add new validation cash customer (Z1) should be unique, also account assignment group should be mandatory for Z1 partner. Not Started", exact=True).locator("#MainContent_gvABAPDevDetails_lnkEdit_240").click()
    page.locator("#MainContent_AllStatus").select_option("10")
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.get_by_text("Development Description Module Interface FRICE Category Priority / Order").click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_AllStatus").select_option("0")
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.locator("#MainContent_AllStatus").select_option("10")
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.locator("#MainContent_AllStatus").select_option("5")
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.locator("span").filter(has_text="Back").click()
    page.get_by_role("row", name="Submit Add new validation cash customer (Z1) should be unique, also account assignment group should be mandatory for Z1 partner. Not Started", exact=True).locator("#MainContent_gvABAPDevDetails_lnkEdit_240").click()
    page.locator("#MainContent_AllStatus").select_option("10")
    page.goto("https://ess.highbartech.com/hrms/procs/ABAP_Object_Tracker_Change_Status_ABAP.aspx")
    page.locator("#MainContent_editform1").get_by_role("listitem").filter(has_text="Planned Start Date").click()
    page.locator("#MainContent_Txt_PlannedPreparationStart").click()
    page.locator("#MainContent_txt_PlannedPreparationFinish").click()
    page.locator("#MainContent_Txt_RevisedActualSubmission").click()
    page.get_by_text("23", exact=True).click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_CalendarExtender4_day_3_6").click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_CalendarExtender4_day_3_6").click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_Txt_RevisedActualSubmission").click()
    page.locator("#MainContent_CalendarExtender3_day_3_6").click()
    page.get_by_text("Actual Finish Date* May,").click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_CalendarExtender4_day_3_6").click()
    page.locator("#MainContent_txt_RevisedActualApproval").click()
    page.locator("#MainContent_CalendarExtender4_day_3_6").click()
    page.locator("#MainContent_LinkBtnBackPopup").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
