; Prefix
; ^ = Ctrl Key          
; ! = Alt Key
; + = Shift Key
; # = Windows Key
; F = Function key
; < = Use left side key of a key pair eg: <+ = left side Shift Key

[Hotkeys]  
MED120="^4"
MED100="^1"
MEQ200="^2"
MEP300="^3"

[MED120]
; Connection name as it appears in SAP Logon (e.g., "PRD - Production")
ConnectionName="ALIMCO DEV S4"
SID="MED"
Client="120"
User="HBTABAP"   
Password="HighbarAlimco^33"

[MED100]
ConnectionName="ALIMCO DEV S4"
SID="MED"
Client="100"
User="HBTADMIN"   
Password="HighbarAlimco^33"

[MEQ200]
ConnectionName="ALIMCO QAS S4"
SID="MEQ"
Client="200"
User="HBTADMIN"   
Password="Abap@Hbt!@#$%987654"

[MEP300]
ConnectionName="ALIMCO PRD S4"
SID="MEP"
Client="300"
User="HBTADMIN"   
Password="Abap@Hbt!@#$%987654"

[ModuleOwners]
MM=Anurag Singh
FI=Ketan Deshpande
SD=Vinit Makwana/Vishal Singh
PP=Hemendra Patidar
QM=Hemendra Patidar
FLM=Prakhar Chaurasiya
BASIS=Prakhar Chaurasiya
HCM=Satyapal Singh
CO=Ketan Deshpande
PS=Ketan Deshpande
PM=Virendra Singh Rathore
ABAP=Jayasurya Lakkoju