#Requires AutoHotkey v2.0

; Hook all keyboard input
$*~a::ShowKey("a")
$*~b::ShowKey("b")
$*~c::ShowKey("c")
$*~d::ShowKey("d")
$*~e::ShowKey("e")
$*~f::ShowKey("f")
$*~g::ShowKey("g")
$*~h::ShowKey("h")
$*~i::ShowKey("i")
$*~j::ShowKey("j")
$*~k::ShowKey("k")
$*~l::ShowKey("l")
$*~m::ShowKey("m")
$*~n::ShowKey("n")
$*~o::ShowKey("o")
$*~p::ShowKey("p")
$*~q::ShowKey("q")
$*~r::ShowKey("r")
$*~s::ShowKey("s")
$*~t::ShowKey("t")
$*~u::ShowKey("u")
$*~v::ShowKey("v")
$*~w::ShowKey("w")
$*~x::ShowKey("x")
$*~y::ShowKey("y")
$*~z::ShowKey("z")

$*~0::ShowKey("0")
$*~1::ShowKey("1")
$*~2::ShowKey("2")
$*~3::ShowKey("3")
$*~4::ShowKey("4")
$*~5::ShowKey("5")
$*~6::ShowKey("6")
$*~7::ShowKey("7")
$*~8::ShowKey("8")
$*~9::ShowKey("9")

$*~F1::ShowKey("F1")
$*~F2::ShowKey("F2")
$*~F3::ShowKey("F3")
$*~F4::ShowKey("F4")
$*~F5::ShowKey("F5")
$*~F6::ShowKey("F6")
$*~F7::ShowKey("F7")
$*~F8::ShowKey("F8")
$*~F9::ShowKey("F9")
$*~F10::ShowKey("F10")
$*~F11::ShowKey("F11")
$*~F12::ShowKey("F12")

$*~Space::ShowKey("Space")
$*~Enter::ShowKey("Enter")
$*~Tab::ShowKey("Tab")
$*~Backspace::ShowKey("Backspace")
$*~Escape::ShowKey("Escape")
$*~Delete::ShowKey("Delete")
$*~Insert::ShowKey("Insert")
$*~Home::ShowKey("Home")
$*~End::ShowKey("End")
$*~PgUp::ShowKey("Page Up")
$*~PgDn::ShowKey("Page Down")

$*~Up::ShowKey("Up Arrow")
$*~Down::ShowKey("Down Arrow")
$*~Left::ShowKey("Left Arrow")
$*~Right::ShowKey("Right Arrow")

$*~LShift::ShowKey("Left Shift")
$*~RShift::ShowKey("Right Shift")
$*~LCtrl::ShowKey("Left Ctrl")
$*~RCtrl::ShowKey("Right Ctrl")
$*~LAlt::ShowKey("Left Alt")
$*~RAlt::ShowKey("Right Alt")
$*~LWin::ShowKey("Left Win")
$*~RWin::ShowKey("Right Win")
$*~CapsLock::ShowKey("Caps Lock")
$*~NumLock::ShowKey("Num Lock")
$*~ScrollLock::ShowKey("Scroll Lock")
$*~PrintScreen::ShowKey("Print Screen")
$*~Pause::ShowKey("Pause")

; Numpad
$*~Numpad0::ShowKey("Numpad 0")
$*~Numpad1::ShowKey("Numpad 1")
$*~Numpad2::ShowKey("Numpad 2")
$*~Numpad3::ShowKey("Numpad 3")
$*~Numpad4::ShowKey("Numpad 4")
$*~Numpad5::ShowKey("Numpad 5")
$*~Numpad6::ShowKey("Numpad 6")
$*~Numpad7::ShowKey("Numpad 7")
$*~Numpad8::ShowKey("Numpad 8")
$*~Numpad9::ShowKey("Numpad 9")
$*~NumpadDot::ShowKey("Numpad .")
$*~NumpadDiv::ShowKey("Numpad /")
$*~NumpadMult::ShowKey("Numpad *")
$*~NumpadSub::ShowKey("Numpad -")
$*~NumpadAdd::ShowKey("Numpad +")
$*~NumpadEnter::ShowKey("Numpad Enter")

; Symbols
$*~`;::ShowKey(";")
$*~'::ShowKey("'")
$*~,::ShowKey(",")
$*~.::ShowKey(".")
$*~/::ShowKey("/")
$*~\::ShowKey("\")
$*~[::ShowKey("[")
$*~]::ShowKey("]")
$*~-::ShowKey("-")
$*~=::ShowKey("=")
$*~`::ShowKey("` (Backtick)")

ShowKey(keyName) {
    ; Get scan code and virtual key code
    vk := GetKeyVK(keyName)
    sc := GetKeySC(keyName)
    
    msg := "Key Pressed: " keyName "`n"
        . "VK Code (Hex): 0x" Format("{:02X}", vk) "`n"
        . "VK Code (Dec): " vk "`n"
        . "SC Code (Hex): 0x" Format("{:03X}", sc) "`n"
        . "SC Code (Dec): " sc
    
    ToolTip(msg)
    SetTimer(() => ToolTip(), -2000)
}